### ISSUE TITLE
Thermometer graphics

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/dashboard#139]
Noticed that if the thermometer widget is drawn larger scale in a dashboard, the thermometer bulb (at the bottom) shows a white rectangle - see screenshot below.

![thermo](https://user-images.githubusercontent.com/973580/30242920-ec423c4c-9597-11e7-9441-8638125fd663.PNG)

**Comment by thib66** [comment]
Hello,
@Paul-Reed , 
thanks for pointing the problem.
The issue should be fixed with #141 .
Let me know if it works for you.
Regards,
Aymeric
