### ISSUE TITLE
Dashboards NEW button not working

### ISSUE THREAD

**Issue by rumenchristov** [emoncms/dashboard#143]
Hi!
In a fresh installation from today:

Version | 9.8.27 \| 2017.12.21
Modules | Administration \| Dashboard v1.1.1

in the Dashboard menu, pressing the NEW button, it does not create a new empty dashboard.
What could be the reason for this?
BR
Rumen
================================
No dashboards created
Maybe you would like to add your first dashboard using the button bellow.

+NEW

**Comment by glynhudson** [comment]
Sorry, I'm unable to recreate on Emoncms 9.8.27 / 9.8.28. Does you browser dev console give any clues?

**Comment by rumenchristov** [comment]
With the last update, that I checked the Database, the problem is solved. Many thanks!
Rgds
