### ISSUE TITLE
 Dashboard Button not working

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/dashboard#164]
i try to use button in dashboard i got some error “field could not be updated”
how to update feed value in when i press button in dashboard…

**Comment by TrystanLea** [comment]
I've fixed a different issue with this widget and it seems to be working ok, please reopen this issue if the problem continues.
https://github.com/emoncms/dashboard/commit/ccce88418492bc5d4cee61124a162b9aca079afc
