### ISSUE TITLE
feedvalue alignment

### ISSUE THREAD

**Issue by pb66** [emoncms/dashboard#166]
Would it be possible to have a choice of left, centre, right (auto?)  alignment for the feed value widgets?

Sometimes we want to keep them in a nice left aligned column, sometimes we want to keep the values within left and right borders. Currently the alignment is a little hap hazard at times.

See https://community.openenergymonitor.org/t/using-feed-data-in-textbox/8322/12?u=pb66

**Comment by thib66** [comment]
Hello, please could you confim that the issue can be closed?
It seems that we have now the ability to select the aligment.
Thanks,
Regards,
Aymeric

**Comment by thib66** [comment]
Hello @pb66 @emrysr @Paul-Reed @TrystanLea . Can we consider that the issue is fixed? Ability to select the alignment has been added for all the text widgets (feedvalue, dewpoint, humidex, ...).
Regards,
Aymeric
