### ISSUE TITLE
feedvalue widget text resolution is "fuzzy"

### ISSUE THREAD

**Issue by pb66** [emoncms/dashboard#167]
The text produced by the feedvalue widget is not as crisp as the other elements on the page

See https://community.openenergymonitor.org/t/using-feed-data-in-textbox/8322/12?u=pb66

![image](https://user-images.githubusercontent.com/5606042/44689786-993fc900-aa50-11e8-90d0-8576ff82903f.png)

**Comment by thib66** [comment]
Hello @pb66 @emrysr @Paul-Reed @TrystanLea . Can we consider that the issue is fixed? The text is no longer blurred for all the text widgets (feedvalue, dewpoint, humidex, ...).
Regards,
Aymeric
