### ISSUE TITLE
fresh install cant rename dashboards or set any flags

### ISSUE THREAD

**Issue by dafyddhirst** [emoncms/dashboard#172]
Ive just performed an install as per 
https://github.com/emoncms/emoncms/blob/master/docs/RaspberryPi/readme.md
then installed graph and dashboard
updated database under admin
now i can create dashboards but not rename them or set public flag etc as the changes revert back automatically to what they were.
any ideas?

the log shows below when making a dash public

PHP Notice:  Undefined property: stdClass::$alias in /var/www/emoncms/Modules/dashboard/dashboard_model.php on line 132, referer: http://172.16.18.165/emoncms/dashboard/list
[Sun Oct 07 09:11:59.793540 2018] [:error] [pid 648] [client 172.16.18.202:61748] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strtolower() in /var/www/emoncms/Modules/dashboard/dashboard_model.php:247\nStack trace:\n#0 /var/www/emoncms/Modules/dashboard/dashboard_model.php(132): Dashboard->make_slug(NULL)\n#1 /var/www/emoncms/Modules/dashboard/dashboard_controller.php(71): Dashboard->set(1, 2, Object(stdClass))\n#2 /var/www/emoncms/core.php(64): dashboard_controller()\n#3 /var/www/emoncms/index.php(191): controller('dashboard')\n#4 {main}\n  thrown in /var/www/emoncms/Modules/dashboard/dashboard_model.php on line 247, referer: http://172.16.18.165/emoncms/dashboard/list

this is only present in the master branch 

stable seems ok

**Comment by EA2EGA** [comment]
I had the same problem on Debian 9, till I installed the php7.0-mbstring
package with apt.
I was going to report it but I forgot to do it......

Hau idatzi du Paul (notifications@github.com) erabiltzaileak (2018 urr. 7,
ig. (16:25)):

**Comment by dafyddhirst** [comment]
I can confirm installing php7.0-mbstring and rebooting fixes the issue :) 
Thanks

**Comment by glynhudson** [comment]
This issue only seems to effect php7 since on php 6.7 mbstring used to be built into libapache2-mod-php5. 

I've added php7.0-mbstring to the Emoncms dashboard install guide and the Emoncms core dependency. It's better that mbstring is installed from the beginning since it's probably needed by other modules. 

Thanks for reporting :+
