### ISSUE TITLE
Custom Widget Creation to dashboard 

### ISSUE THREAD

**Issue by kumarmohan7** [emoncms/dashboard#200]
Hi,

How to create custom Widgets,
I need get number in dashboard & update to feed data…

Example:-
1. slider widget
2. enter number in edit box widget

Please help to create custom Widget for dashboard

Thanks.
Mohankumar

**Comment by TrystanLea** [comment]
Hello @kumarmohan7 
The best place to start is to make clones of existing widgets to get an idea for how they work, tweak the code until it starts to make sense. The feed value widget is a good example of a basic widget:
https://github.com/emoncms/dashboard/blob/2.0.3/widget/feedvalue/feedvalue_render.js

or this button widget updates feed data as a result of user interaction:
https://github.com/emoncms/dashboard/blob/2.0.3/widget/button/button_render.js
