### ISSUE TITLE
sidebar banch: 'all dashboards' selected 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/dashboard#206]
- When testing sidebar branch when any dashboard is selected "All dashbaoards" are also selected:

![c127d44ca17d33a4cf51d3aa5fb9372034a4fb00](https://user-images.githubusercontent.com/758844/55668804-78e9af80-5866-11e9-8130-379328e0cf9c.png)

- The title of the dashboard menu should be renamed from "Dashboard" > "Dashboards" 

- The "main" dashboard (default) should be selected when the user clicks on the dashboard icon

![Emoncms - dashboard list](https://user-images.githubusercontent.com/758844/55668847-16dd7a00-5867-11e9-96f7-227b56438157.png)

Thanks to @bornpin for these suggestions:

https://community.openenergymonitor.org/t/beta-new-emoncms-sidebar-navigation-layout-feedback-request/10435/32?u=glyn.hudson

**Comment by emrysr** [comment]
all dashboards link now not incorrectly highlighted:
![delwedd](https://user-images.githubusercontent.com/1466013/56962358-432aa480-6b4e-11e9-8464-3982c0dea8ca.png)

the "main dashboard" has been relabeled to "default".
The default dashboard is hightlighted in the list and appears on all pages as the first bookmark in the sidebar
![delwedd](https://user-images.githubusercontent.com/1466013/56962560-cc41db80-6b4e-11e9-8b92-49c371bf1a3b.png)

**Comment by emrysr** [comment]
fixed now in master branch
