### ISSUE TITLE
In full screen mode the 'view' icon is missing on the All Dashboards page 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/dashboard#213]
The 'view' (eye) icon is missing when viewing All dashboards page in full screen:

![Screenshot 2019-05-22 at 12 08 10](https://user-images.githubusercontent.com/758844/58170087-65fe3380-7c8a-11e9-824a-d4d5d641fc97.png)
![Screenshot 2019-05-22 at 12 08 01](https://user-images.githubusercontent.com/758844/58170088-65fe3380-7c8a-11e9-96de-d1ab670dab65.png)

**Comment by emrysr** [comment]
this view is not responsive enough to see the last column. i'll try and see if this can be changed to stop the need to scroll right
