### ISSUE TITLE
No "New" button to add new dashboard

### ISSUE THREAD

**Issue by tmedicci** [emoncms/dashboard#219]
[Commit 385c](https://github.com/emoncms/dashboard/commit/385c584f8b78b6dddf50d8d1aec590c551a25dab) has no "New" button to add a new dashboard, only showing available dashboards list. Simply checking-ou to [commit d54e](https://github.com/emoncms/dashboard/commit/d54e78adcb6b0b3ffd4de09f4cad5f7a15e51135) solves the problem.

**Comment by pb66** [comment]
There maybe a related case on the forum too https://community.openenergymonitor.org/t/ubuntu-18-04-server-on-beaglebone-dashboard-not-working/11190/2?u=pb66

**Comment by iotlibre** [comment]
Thank you very much Tiago. I have been trying to solve the problem until I found your comment
