### ISSUE TITLE
Update AntiXSS to php7 (review and test)

### ISSUE THREAD

**Issue by pb66** [emoncms/dashboard#229]
Should this line https://github.com/emoncms/dashboard/blob/2.0.3/dashboard_model.php#L95
```
            $axdir = "Modules/dashboard/AntiXSS/php5";
```
be dynamically set if we are continuing to support php5 or maybe just edited to php7 if php5 is no longer (or rarely?) supported?

**Comment by chaveiro** [comment]
PHP7 is no longer supported right? Please close.
