### ISSUE TITLE
[dashboards restored from backup files coming from old versions] A simple modification of an existing element of the dashboard is not restoring the new routes correctly in the alias field of the dashboard table

### ISSUE THREAD

**Issue by alexandrecuer** [emoncms/dashboard#238]
I've just restored on a brand new system an zip created with a old version of emoncms : low-write 9.8.28 | 2018.01.27
restored dashboards are not showing correctly :
![image](https://user-images.githubusercontent.com/24553739/65584280-edcdb480-df80-11e9-8219-dc3e4a4ec52a.png)
but edition is fine : 
![image](https://user-images.githubusercontent.com/24553739/65584472-3b4a2180-df81-11e9-8448-342e2a00d86f.png)

in the alias field of the dashboard table, routes are wrong eg : /emoncms/vis/multigraph?embed=1&amp;mid=31

this is normal because the metadatas are coming from an old version

with the new version, they should be only something like /vis/multigraph?embed=1&amp;mid=31

A simple modification of an existing element of the dashboard should be able to restore the new routes correctly in the alias field of the dashboard table....anyway, it is not working that way which can be annoying for users....
updating an existing element
![image](https://user-images.githubusercontent.com/24553739/65585176-549f9d80-df82-11e9-956b-6fa2756509e0.png)
saving the dashboard
![image](https://user-images.githubusercontent.com/24553739/65585308-8dd80d80-df82-11e9-8b8d-269d749d73a9.png)
view is still in error
![image](https://user-images.githubusercontent.com/24553739/65585358-a3e5ce00-df82-11e9-9df3-e31dbe80cdbd.png)

you need to add a new element (graph,multigraph) to the dashboard and to save the dashboard. Configuring the new element is not needed....
![image](https://user-images.githubusercontent.com/24553739/65585575-f9ba7600-df82-11e9-8d69-0ce3794fd76d.png)
 
After saving the whole alias field gets correctly updated and the dahsboard is correctly viewed
![image](https://user-images.githubusercontent.com/24553739/65585674-22db0680-df83-11e9-9648-6eda929b3d07.png)

**Comment by TrystanLea** [comment]
Hello @alexandrecuer I introduced an automatic redirect October 14th to emoncms core that is intended to fix this problem, I will close for now assuming this is working, please re-open if needed https://github.com/emoncms/emoncms/commit/a21a4626f99c55a621a95aa68fca5fd68a001359
