### ISSUE TITLE
fullscreen mode

### ISSUE THREAD

**Issue by emrysr** [emoncms/dashboard#244]
related to emoncms issue: https://github.com/emoncms/emoncms/issues/1478

option to hide menus on specific dashboards.

**Comment by chaveiro** [comment]
Previously on v9.8  the top menu only showed when you're on the top of the screen or scrolling up.
If there is a scroll bar at the right and you're not at the top not nor scrolling up, menu is hidden.

Please recover this behaviour on v10.

**Comment by chaveiro** [comment]
fixed in https://github.com/emoncms/dashboard/pull/277

**Comment by chaveiro** [comment]
This can be closed
