### ISSUE TITLE
"New" button isn't working

### ISSUE THREAD

**Issue by vbenhur** [emoncms/dashboard#251]
Hello, 

I installed v2.0.3 but the "New" button isn't working.
When I click nothing happens. 
Maybe is there any other config to do?

Thanks

**Comment by pb66** [comment]
Have you tried clearing the browser cache (ctrl-f5) since updating?

Otherwise you are better off visiting the OEM forum for assistance in the first instance.

https://community.openenergymonitor.org

**Comment by vbenhur** [comment]
Already did this and nothing.
Ok, I will ask there.

Thanks

**Comment by pb66** [comment]
See https://community.openenergymonitor.org/t/dashboard-button-new/13209?u=pb66
