### ISSUE TITLE
Show multiple dasboards with rotating

### ISSUE THREAD

**Issue by trentasis** [emoncms/dashboard#252]
Hi,

I like to know how can I show mutiple dasboards with a rotating policy, is this possible?
Like nagvis is an example

Thanks

**Comment by glynhudson** [comment]
This is not currently possible using Emoncms, however you could use something like: https://www.screenly.io/

Screenly can be run on a RaspberryPi and can rotate a display between several web pages. There is a free open-source version. You would need to make your Emoncms dashboards public with a UL or put the read API key in the address e.g 

`https://emoncms.org/dashboard/view&id=XX&apikey=XXXXXXXXXXXXXXXXXX`
