### ISSUE TITLE
battery font color

### ISSUE THREAD

**Issue by DarkenLight** [emoncms/dashboard#254]
when battery level changes, it also change the background of the texts. So, if we set a dark color for the text it become unreadable when battery is full, and if we set a lighter color its become unreadable during low battery. it can be seen in the below pictures.

dynamic color change is not wanted, may be white border for the text can solve this issue.
![Opera Snapshot_2020-03-12_180018_eliozestpower com](https://user-images.githubusercontent.com/37840366/76521766-7981c180-648b-11ea-84b0-68ffb09ce40a.png)
![Opera Snapshot_2020-03-12_180050_eliozestpower com](https://user-images.githubusercontent.com/37840366/76521770-7ab2ee80-648b-11ea-9ba9-ee237e05beeb.png)

**Comment by glynhudson** [comment]
I agree, I've also noticed this issue. A possible easier fix could just be to show the % value outside at the bottom or top of the battery.

**Comment by Ultimate-Virus** [comment]
yes that could be a solutions. but I have another pretty easy solution.
what if we reverse the gradient. like this. 
![Battery](https://user-images.githubusercontent.com/37840366/76683764-a1f4f180-662c-11ea-9d0b-bedd1bf8cbd9.png)

**Comment by glynhudson** [comment]
Nice, that's good idea. I would be happy to accept a pull request for this.

**Comment by thib66** [comment]
Hello,
would you like to reverse systematically the gradient for all the widgets already created (and for the new ones as well), or would you like to have an option in order to choose if the gradient shoud be reversed? 
Thanks a lot for your answer.
