### ISSUE TITLE
Stacked Solar & Stacked graphs are fixed at 5yr view 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/dashboard#255]
The stacked Solar & Stacked graphs are fixed at 5yr view, there is not way to adjust this. This makes these views almost useless, unless you have 5yrs of data! This is a shame since these are useful views if a time frame setting was added. 

![Selection_351](https://user-images.githubusercontent.com/758844/76543804-efcbf700-647e-11ea-9e89-0b8468c7bad2.jpg)

**Comment by TrystanLea** [comment]
Perhaps loading the feed start date via /feed/getmeta.json would be a good approach here, that way the view initial monthly view would cover the period of data available?

**Comment by TrystanLea** [comment]
Fixed in latest master: https://github.com/emoncms/emoncms/commit/6cbe646d91eab708a9af1dcb62b2ac6988e48cff
