### ISSUE TITLE
"Add New" in sidebar

### ISSUE THREAD

**Issue by emrysr** [emoncms/dashboard#259]
Should there be an `Add New` option in the sidebar like this...
![image](https://user-images.githubusercontent.com/1466013/76861391-718f9c00-6854-11ea-95ed-0474d0548cef.png)

Currently users go to `All Dashboards` to see the button for `Add New`

Would require a new entry in the menu file under "All Dashboards"...
https://github.com/emoncms/dashboard/blob/master/dashboard_menu.php#L51

and pass a parameter to the view from the controller to display the "new item" form
https://github.com/emoncms/dashboard/blob/master/dashboard_controller.php#L32
eg. `dashboard/list/new`
that parameter could auto run the function `app.addNew()` which would add a new line to the list on load.

**Comment by glynhudson** [comment]
Agree, this would be a good addition and would make dashboards consistent with Apps

**Comment by chaveiro** [comment]
I would call "All dashboards" "Configuration"  and keep the new button on the configuration page.
Also recovering this https://github.com/emoncms/dashboard/issues/267
