### ISSUE TITLE
Error message when displaying dashboard in embedded mode - menu v3

### ISSUE THREAD

**Issue by thib66** [emoncms/dashboard#269]
hello,
I have a dasboard embedded in a frame of a website.
when the main page is displayed I get the following error message : 
![image](https://user-images.githubusercontent.com/29287201/121159877-e0875500-c84b-11eb-9b10-59f0f869e937.png)
In embedded mode the menu is not present and the call of menu.min_l2(); fails...
Could we have a fix ?
Thanks in advance

**Comment by TrystanLea** [comment]
Hello @thib66 sorry about this one, it's now fixed!
