### ISSUE TITLE
Feedvalue_render.js

### ISSUE THREAD

**Issue by PetrP2B** [emoncms/dashboard#270]
Hi, I tried to use the feedvalue widget, but I couldn't get the correct color, by value. I found that in feedvalue_render.js (line 271) the value for the upper limit is multiplied by 2. After removing the multiplication, the coloring works correctly according to the set limits.

if($(this).attr("threshold1")!=undefined && $(this).attr("threshold1")!="" && $(this).attr("threshold2")!=undefined &&$(this).attr("threshold2")!=""){
            var limit1 = $(this).attr("threshold1") || 60;
            var limit2 = $(this).attr("threshold2") || 120;
            if (val < limit1) {
               textcolor = feedvalue.attr("colour1")|| "#019F62";
            } else if (val > limit2) {
               textcolor = feedvalue.attr("colour3")|| "#F70511";
            } else {
               textcolor = feedvalue.attr("colour2")|| "#FF8425";
Petr

**Comment by TrystanLea** [comment]
Thanks @PetrP2B I've merged in the fix for this by @chaveiro, cheers for flagging!
