### ISSUE TITLE
move lots of elements or add space

### ISSUE THREAD

**Issue by daniu-de** [emoncms/dashboard#281]
Hi
I got a dashboard with lots of sensor data on the top and the graphs for each sensor below + the same data again.

Now I added some sensors to my system and would like to extend the list on top. At the moment I do not see another way than to move ALL elements below the list to get space for the extra sensor data ... that is lots of work ... Does anybody see another way?

**Comment by chaveiro** [comment]
Fix on 2.4.0 here https://github.com/emoncms/dashboard/pull/284/commits/8055c0f51ef6030e3f9c2192de6a933fb189ec6b
Adds support for select box for drag multiple widgets
See demo:
![edit dash rezise](https://github.com/emoncms/dashboard/assets/4527135/e7d1910d-8b80-4c5d-869c-2a6ec5e3adbe)

**Comment by chaveiro** [comment]
Please close it's implemented.
