### ISSUE TITLE
Dashboard stays 'loading'

### ISSUE THREAD

**Issue by Jaco69** [emoncms/dashboard#3]
After upgrade from v8.5.1 XT to 9.5.1 | 2016.04.28 the dashboard graphs don't show but stay in loading state. See picture:
![dashboard](https://cloud.githubusercontent.com/assets/5123863/15251110/230b2556-1928-11e6-8123-d00927852c91.png)
Everything else seems fine. I use MySQL for feed values.

After a roll back everything is back to normal.
If 9.5.1 is in /var/www/emoncms_new but /var/ww/emoncms is v8.5.1 XT it works when I use URL http://localhost/emoncms_new (but older version Dashboard is used)

**Comment by RDCH106** [comment]
Did you update the database from the admin area?

Is the dashboard the only thing not working?

**Comment by Jaco69** [comment]
Hi,

Yes I updated the database.
I couldn't get any graph to work, myelektric also didn't work. Except
graphs I haven't found any other problem. All menu's work.

Br,
Jaco

2016-05-27 10:24 GMT+02:00 Rubén de Celis Hernández <
notifications@github.com>:

**Comment by RDCH106** [comment]
Take a look to the log

**Comment by Jaco69** [comment]
log is empty

**Comment by Jaco69** [comment]
Seems only zoom, simple zoom and the apps are affected, Other graphs are OK. I was only using the zoom on dashboard and my elecric app.
Can it be that MYSQL feeds are broken for zoom?
