### ISSUE TITLE
Floating Palette - move palette offscreen

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/dashboard#43]
_I thought that this issue had been fixed earlier, but I may be wrong?_

The palette can be dragged off of the dashboard workspace and cannot be recovered without exiting the edit mode by selecting a different menu item, losing any changes that had been made.

Not a major issue! but nice to avoid.

![offscreen](https://cloud.githubusercontent.com/assets/973580/19496574/03d66a7c-9580-11e6-9c55-d170ef4d224f.gif)

**Comment by glynhudson** [comment]
Haha yes, I've just managed to successfully 'loose' the pallet off the screen which means any changes made cannot be saved. This would be suboptimal if a lot of changes to a dashboard has just been made. If this could be fixed it would be great @firefox7518 ? 

 I love the new buttons btw. They have 'grown' on me 👍

**Comment by firefox7518** [comment]
Tried to fix that with PR #60
I think its ok to stop it from moving outside on top and left positions but it should freely float to the right and down as it creates a normal scrollbar and is always accessible.

Let me know if this is ok. this screen position grabbing things are horrible :-) At least for me as a novice.

**Comment by glynhudson** [comment]
A good start! This has fixed the constraints in the upwards Y-direction, but it's still possible to move the palette off the screen in the bottom Y-direction on in the right x-direction. Do you see same effect? See my screen cast: https://youtu.be/gwbXd1N-0Ic

**Comment by Paul-Reed** [comment]
Can't you use the X & Y scroll bars to retrieve the palette?
I'm not in a position to test, but looking at your video, the scroll bars
appear to be populating.

**Comment by firefox7518** [comment]
Glyn, yes, as stated in the PR I just limited the upper and left area because when moving it down and right the scrollbar shows up and has the normal behavior. I would find it a little odd if you have to first place a widget on the dashboard and then move it down or right before you are able to move the palette more down or to the right so I left this open and free.

**Comment by glynhudson** [comment]
Ah yes, sorry my bad. Yup, it does what it says on the tin. This is a big improvement since it's now not possible to totally lose it and not be able to save changes. I will merge 👍

**Comment by firefox7518** [comment]
If you guys think it should not move to the right and down below the dashboard area I of course can bound it too :-)
