### ISSUE TITLE
Dashboard editor blank and unresponsive

### ISSUE THREAD

**Issue by CNek** [emoncms/dashboard#50]
Hello there,
So with EmonCMS 9.7.4 + Fresh clone of dashboard module, on a fresh setup.
I have some inputs feeds kicking in.
I create a new dashboard, then i cannot create new components on the canvas.

I get :

`SyntaxError: missing ) after argument list -  vis_render.js:45:350`

and

```
TypeError: fn is not a function - render.js:44:22
    render_widgets_init *******/render.js:44:22
    <anonyme> https://*****.com/dashboard/edit:249:5
```

Maybe I will try with an older release as it worked for me before on a different installation.

**Comment by Paul-Reed** [comment]
Cannot replicate issue using emoncms 9.7.5

Paul

**Comment by Paul-Reed** [comment]
Do you still have this issue, what have you tried to resolve it?

**Comment by glynhudson** [comment]
I cannot replicate either
