### ISSUE TITLE
Dash Background Dont Save

### ISSUE THREAD

**Issue by Paulf007** [emoncms/dashboard#68]
After you have changed the background color of the dash and then save it will show on the new color as long as you are in "edit" mode , but the moment you go to "preview" mode it changes back to default.

**Comment by Paul-Reed** [comment]
Cannot replicate here with self-build emoncms low-write 9.7.8 | 2016.11.10 & current dashboard master.
Can you recheck please and provide some information about your system, including versions.

Paul

**Comment by Paulf007** [comment]
Hi Paul 
Updated the database through admin.
It is a Windows installed server , server info below:
![2016-12-09_114649](https://cloud.githubusercontent.com/assets/24200183/21044567/4c15517e-be05-11e6-9f0a-3a3a909e50aa.png)
Also when I chnage the default color in the "dashboard_schema.php" it does not update on the dash it self. You have to clone the dash then it will update to the new dash. Also noticed that when you made the dash public you cannot change it to private, The setting will show it as private but as soon as you update the page it will revert back to the public setting. 

Hope this gives you enough info. 
Paul

**Comment by Paul-Reed** [comment]
It sound as though you've made some local changes to the dashboard module?? If so, can you install a 'stock' version of the dashboard module and see if your problem still exists.
Also, is this a new installation, and if not, what led up to this issue - were there any changes made?

**Comment by Paulf007** [comment]
The only thing that I changed was the color value in the dashboard_schema.php , that and a few extra widgets. Could they have an impact?

**Comment by Paulf007** [comment]
Ok tested with the stock standard dash module with the same effect , the dash changes to the selected background but the moment you move out of edit mode it reverts back to default. Where is the values for the dash config stored? Maybe I could look what happens there?

**Comment by Paul-Reed** [comment]
It's stored in MYSQL 
If you look at the respective  'dashboard' table, you will see column called 'backgroundcolor' which should contain the color code in hex.

**Comment by Paulf007** [comment]
Cool I have found it but is that just the default color? Where is the color for every individual dash saved?

**Comment by Paul-Reed** [comment]
As per my post above, each dashboard saved background color is saved in it's respective table in the column 'backgroundcolor'.

Paul

**Comment by Paulf007** [comment]
Hi Paul

Now my limited knowledge is catching up with me but I would then venture as to say that the updated background value is not passed to the dash file in the Sql. 

I also noticed that once a new dash is created you cannot alter the any of the information for that dash created. The only way to change it is to clone the dash and then rename and change the attributes. Could it be that the "dash" table does not accept alterations once a new line is created with the values added?

**Comment by Paul-Reed** [comment]
As per my post above; 'is this a new installation?'
ie, has this ever worked?

**Comment by Paulf007** [comment]
Hi Paul 
Sorry I did not make myself clear. 
Yes it is a new install , I never played with the background before and only noticed the problem now. So it would not be able to say if it worked before.  Is there anything else that I could check to assist? All other features works dash design , widgets , feeds inputs... Only problem seems to be the dash table with in the SQL. Here is a screenshot of the table I don't know it that could help. 
![2016-12-11_163530](https://cloud.githubusercontent.com/assets/24200183/21080772/03429436-bfc0-11e6-900a-84e4caac17ad.png)

**Comment by Paulf007** [comment]
Ok I did some more testing on the Dashboard's 

1) If you create a new blank dash and there is no data in the contents field you are able the change the "public , published values to either 1 or 0 
2) Once there is info in the "content" filed the above values do not change and you need to delete the dash .
3) A New dash background color does not change in the sql even if you save it and it shows on the dash editor. The value does not change in the sql. If you change the value directly in the sql it updates to the dash but not the other way around.  
4) All other features with in the dash do change with out any problems.

Here is some screenshots of the SQL and the dash control:
Dash before edit
![2016-12-11_165236](https://cloud.githubusercontent.com/assets/24200183/21080916/bf9a15f2-bfc3-11e6-93b3-bd257730fcb3.png)
SQL before edit 
![2016-12-11_165251](https://cloud.githubusercontent.com/assets/24200183/21080922/d06edb92-bfc3-11e6-8371-5fe6c37560e2.png)
Dash After Edit 
![2016-12-11_170432](https://cloud.githubusercontent.com/assets/24200183/21080927/e875c20a-bfc3-11e6-8845-49c408c92bd5.png)
SQL after Edit
![2016-12-11_165330](https://cloud.githubusercontent.com/assets/24200183/21080928/f3e052ea-bfc3-11e6-828c-8f2850bff047.png)
 If you refresh the page the menu reverts back to origina.

Best regards
Paul

**Comment by Paul-Reed** [comment]
All that I can think of is either the MYSQL database privileges or the MYSQL user account have not been set up correctly [as per the guide](https://github.com/emoncms/emoncms/blob/master/docs/WindowsInstall.md).
I don't use a Windows environment, but maybe [post in the forum](https://community.openenergymonitor.org/) linking to this thread, and perhaps a Windows user can help you further.

Paul

**Comment by Paulf007** [comment]
Hi Paul 

I will check the privileges in the SQL and give feedback. Also will post on the forum. 
Thank you for taking the time to assist!
Paul

**Comment by Paul-Reed** [comment]
Paul, is there a update on this issue please.

Paul

**Comment by Paulf007** [comment]
Morning Paul

To be honest with holiday season I have not spend much time on Emon. I will
have a look at it now in the new year to see if I can figure something out.

Best regards

Paul

**Comment by rjsc** [comment]
I have performed a new installation in Linux (Ubuntu Server 16.10) and am experiencing the same issue.
Besides not saving the background, any other changes done in the "Dashboard Configuration" window such as Alias, Description or setting as Main are not saved.
However, changing the Alias, or setting as Main in "Setup -> Dashboards" (emoncms/dashboard/list) is saved.

**Comment by rjsc** [comment]
I have the following in my apache log file when I try to change the background:
`PHP Notice:  Undefined index: backgroundcolor in /var/www/html/emoncms/Modules/dashboard/Views/dashboard_edit_view.php`
I simply pulled from the repository and didn't change any file besides settings.php

**Comment by Paul-Reed** [comment]
Have you updated your MYSQL Database?
Setup > Administration > Update database

Paul

**Comment by rjsc** [comment]
@Paul-Reed
My bad. Updated emoncms but not the database.
However the original issue is still present: background is not saved, as any of the settings in "Dashboard Configuration" (grid size, description, main, publiseh, etc). The dashboard content is saved.

**Comment by rjsc** [comment]
What bugs me is that changing any configuration in this screen doesn't get saved
![dashboard_config](https://cloud.githubusercontent.com/assets/5718629/25942124/d5e35ad0-3633-11e7-936c-71765d8d48fe.PNG)
However, any change to the same dashboard in the following screen is saved
![dasboards](https://cloud.githubusercontent.com/assets/5718629/25942276/55e5d514-3634-11e7-83c5-e9587c694274.PNG)

**Comment by pb66** [comment]
@rjsc Can you try changing the background colour again, but when you "save" and exit the pop-up "dashboard Configuration" page, can you try clicking the green "not modified" button.

I have seen some pretty erratic behaviour when saving background colours too, is this behaviour consistent every time for you?

**Comment by rjsc** [comment]
@pb66 Clicking the green "not modified" button results in the error described in [https://github.com/emoncms/dashboard/issues/31](url)
If I change something in the dashboard itself to get the "changed press to save" button and save it with the background color changed it still gets back to the default blue color.
The behavior is consistent. Saving anything from the "Dashboard Configuration" fails every tiime.

**Comment by firefox7518** [comment]
Hmm must be a long existing issue. Even my old 8.4 instance which I did not update since then has this issue. What I get in F12 Chrome console is:
![image](https://cloud.githubusercontent.com/assets/12048408/26391174/d5da7342-4061-11e7-952d-b68846d4cdcc.png)
