### ISSUE TITLE
Unable to switch back to view mode

### ISSUE THREAD

**Issue by MopsiMauser** [emoncms/dashboard#70]
When you are configuring your dashboard, you are unable to switch back to view mode via the button. At least with Firefox and IE. But it does work with Chrome. I think the problem is the link within a button, which is not recognized by these browsers without an OnClick event. One solution could be a provided OnClick event on the button, which sets the location via javascript.  The problem is located in dashboard_edit_view.php at line 49.

**Comment by Paul-Reed** [comment]
I'm seeing the same.
Andreas @firefox7518 are you able to sort pls?

Paul

**Comment by firefox7518** [comment]
Created PR https://github.com/emoncms/dashboard/pull/71 please retest.

**Comment by Paul-Reed** [comment]
Fixed by #71
