### ISSUE TITLE
Hiding the editing cog when not logged in

### ISSUE THREAD

**Issue by pb66** [emoncms/dashboard#81]
See ["Embedding emoncms into wordpress"](https://community.openenergymonitor.org/t/embedding-emoncms-into-wordpress/4015?u=pb66) on the OEM forum.

It would be nice to only see the dash editing "cog" when logged in.

**Comment by Paul-Reed** [comment]
Any thoughts Andreas? @firefox7518 

Paul

**Comment by firefox7518** [comment]
Will try to find a solution on the weekend but if someone else already knows how to do it please feel free to add it :-)

**Comment by firefox7518** [comment]
https://github.com/emoncms/dashboard/pull/84 Created a PR for my hiding solution.
The icon should not be available now when your are logged out. You have to log in to see it.

**Comment by Paul-Reed** [comment]
Fixed by https://github.com/emoncms/dashboard/pull/84
