### ISSUE TITLE
Aliases not working with public dashboards

### ISSUE THREAD

**Issue by pb66** [emoncms/dashboard#82]
See ["Accessing public dashboard is not possible using alias "](https://community.openenergymonitor.org/t/accessing-public-dashboard-is-not-possible-using-alias/4075?u=pb66)

http://emon/emoncms/dashboard/view?id=4 works publicly and when logged in

http://emon/emoncms/dashboard/view/name only works when logged in

the alias also works ok when used with an apikey eg

http://emon/emoncms/dashboard/view/name&apikey=abc123def456

**Comment by glynhudson** [comment]
Thanks for reporting. Is this due to a recent change? I.e did alias work previously?  I can confirm that I can re-create this issue. 

Dashboard URLs work differently on emoncms.og, `dashboard/view` is not needed and alias works e.g. https://emoncms.org/beehive/live

**Comment by chaveiro** [comment]
"dashboard/view" is not needed also on local instalations, use "username/alias"

**Comment by Paul-Reed** [comment]
No update since last comment 24th July, safe to assume that alias working as intended & close?
// @pb66

**Comment by pb66** [comment]
Yes this can be closed.
Chaveiro's comment make total sense as without a userid, dash id or apikey there is no way of determining the actual dash being requested unless we were to make dash aliases unique (across the whole server not per account).

My set up is significantly different now so I cannot test to confirm.
